name: Trent Ventura
favicon: null
layout_spectrum: 0.572393044596538
typography_spectrum: 0.3731653345748782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.11844026576727629
  lightness: 0.5528078100178391
  saturation: 0.9338294453918934
  rhythmicContrast: 0.9741263487376273
purpose: []
