name: Trent Ventura
favicon: null
layout_spectrum: 0.00361
typography_spectrum: 0.75
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f2'
    - '#5e564f'
    - '#999592'
    - '#dbc3ad'
    - '#ff7065'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
