name: Mowglife
favicon: null
layout_spectrum: 0.38372
typography_spectrum: 0.75
title: '| SUP | Surf | Sail | Photography | Carpentry | Art'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#84817c'
    - '#3b3c41'
    - '#7cb6dc'
    - '#1a070d'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
